### ISSUE TITLE
setup: allow configuring the number of cores used by why3

### ISSUE THREAD

**Issue by Armael** [creusot-rs/creusot#1011]
Currently the why3 config file generated by `creusot setup` makes why3 use its default number of parallel solver processes, which is 2. It would probably be nicer to:
- by default, have `creusot setup` generate a why3 config file with `running_provers_max` equal to the number of cores of the machine
- add a command-line option to `creusot setup` to allow tweaking this number if needed

**Comment by xldenis** [comment]
Agreed, if we expose a CLI flag for this are there any other options we might want to expose at the same time?

**Comment by claudemarche** [comment]
Beware that changing the default time limit and memory limit has not impact on strategies level 0, 1, 2, 3, which have their own time and memory limit.

On the other hand, the `why3.conf` is the right place to insert other strategies if you think you have better ones than the 4 default ones.

**Comment by sarsko** [comment]
There's probably more, here's the `main` from the `why3.conf` I've been using:
```
[main]
magic = 14
memlimit = 16000
running_provers_max = 8
timelimit = 120
```

Somewhat related: would it be worth to have Creusot look for a `why3.conf` in the project/crate root and include that (ala `--extra-config="$CRATE_ROOT/why3.conf"`)?

**Comment by xldenis** [comment]
> Somewhat related: would it be worth to have Creusot look for a why3.conf in the project/crate root and include that (ala --extra-config="$CRATE_ROOT/why3.conf")?

I do think this is a good idea in general, I think having project specific Creusot configuration (ie to load custom strategies) will be something we inevitably want to have, but I think @Armael is intentionally being less ambitious. A low effort change would be for `creusot` to forward an `extra-config` flag so that you could set up that additional config yourself easily. 

> On the other hand, the why3.conf is the right place to insert other strategies if you think you have better ones than the 4 default ones.

This is something that I think is highly worthwhile, but we are also exploring `why3find` which comes with its own notion of 'strategies'.
