### ISSUE TITLE
derive Clone emits invalid coma

### ISSUE THREAD

**Issue by nishanthkarthik** [creusot-rs/creusot#1074]
Using creusot 9a4c896bf789730c24f719a0e60560aed3310f91

```rs
#[derive(creusot_contracts::Clone)]
pub struct R<T: creusot_contracts::Clone>(std::collections::BTreeMap<T, usize>);
```

generates 

```ocaml
module Alloc_Collections_Btree_Node_Marker_Owned_Type
  type t_owned  =
    
  
  function any_l (_ : 'b) : 'a
end
module Alloc_Collections_Btree_Node_Marker_LeafOrInternal_Type
  type t_leaforinternal  =
    
  
  function any_l (_ : 'b) : 'a
end
```

**Comment by xldenis** [comment]
You're completely correct, but the issue here is actually with the usage of the `BTreeMap` which contains the empty enum `LeafOrInternal`, which isn't supported by creusot currently. 

You can see how to work around this here: https://github.com/creusot-rs/creusot/blob/master/creusot/tests/should_succeed/ite_normalize.rs#L7-L53 

I hope that this error will completely disappear soon though, there are a few changes in the pipeline which should resolve it entirely before you (as a user) have to deal with it.

**Comment by nishanthkarthik** [comment]
Thanks, marking the struct `#[trusted]` and implementing the trusted Clone by hand works for me.
