### ISSUE TITLE
Add provenance information for impl hashes

### ISSUE THREAD

**Issue by Lysxia** [creusot-rs/creusot#1137]
Impls are now non-ambiguously encoded as hashes in coma identifiers, but then it's not really easy for an external tool or for humans to guess the origin of a given coma module, or conversely the translation of a given rust function, unless you reuse or replicate the hashing function that produces the hashes.

I'd like to make this information more easily accessible by showing the impl type in the output next to each module that contains a hashed impl.

```
impl MyType {
   fn f() { ... }
}
```

would generate

```
module M_mylib__qyi1234567890__f (* mylib::MyType *)
```

I've got a branch that does this, but before making a PR I'm wondering if there's a better solution, or any details to bikeshed.

For one thing, my implementation outputs the qualified types because that's what I have access to. It may be easier to read the types as written in the source instead, is there an easy way to get that from the rustc API?

**Comment by jhjourdan** [comment]
I think this is a good idea, but I have several remarks:

1- Is it possible to attach some location information (line numbers) to modules? If so, then it may be good to do that in addition to comments, because this can be integrated with various tools (Why3ide, Creusot plugin for VScode...)

2- I think fully qualified types are good enough for the comments. One may even argue that types are they occur in the source are ambiguous and should be avoided.

**Comment by xldenis** [comment]
>  Is it possible to attach some location information (line numbers) to modules?

Yep you can add a span after the identifier in a module, I'm pretty sure you can after _any_ identifier. However, a cursory check seems to indicate that path resolution is handled differently for module names? The paths for identifiers inside modules are relative to the session file while those in module names are relative to the CWD.

**Comment by jhjourdan** [comment]
Well, then let's open a Gitlab issue?
