### ISSUE TITLE
Operations on `Int` in ghost code

### ISSUE THREAD

**Issue by arnaudgolfouse** [creusot-rs/creusot#1271]
So right now it is not possible to perform arithmetic operation on `Int` in ghost code, e.g. the following:
```rust
ghost! {
    let x = 1int;
    let y = 2int;
    let z = x + y;
};
```
Fails, because `+` on `Int` is a logic-only operation.

**Comment by arnaudgolfouse** [comment]
As I see it, we might provide an immediate solution by defining methods `x.add_ghost(y)`, `x.sub_ghost(y)`, etc. in `creusot_contracts`

But this does put some pression again on the need to define an operation in both the logic and program world.

**Comment by xldenis** [comment]
I think that's a pragmatic solution, it's low commitment and enabled further experimentation

**Comment by jhjourdan** [comment]
A more long term solution (but nevertheless not so difficult to implement) is to implement the various traits for arithmetic operators for Int. This is sound because one can only call them with an Int as parameter, and one can only have an Int in ghost code.

In order to distinguish these implementations from the logical ones, we will need to add `AddLogic` and friends, and use them when translating pearlite.

This will fix another problem @laurentder has where we expect these operators to raise a compile time error when used in pearlite for machine integers.
