### ISSUE TITLE
`creusot-contracts` should be tested in CI

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot#368]
We should actually generate the MLCFG and prove all the obligations in `creusot-contracts`. At the moment everything is `#[trusted]` but we should still check.

**Comment by xldenis** [comment]
Additionally, it would be good to have a systematic way to validate external specifications... I know they are trusted and thus fundamentally axioms, but in some cases they can be re-implemented in terms of other more primitive operations and this would at least help ensure that the _specification_ itself is not completely incoherent.

**Comment by arnaudgolfouse** [comment]
Here is my short attempt to check if creusot-contracts is actually provable. I used the command
```sh
cargo build # done once to build cargo-creusot
./target/debug/cargo-creusot creusot why3 ide -- -p creusot-contracts
```

I only used auto. I did not try any manual tactics for now. Here is a summary of proofs that did not pass and why:

- [ ] `FSet::ext_eq`: we don't have access to `set.Fset.extensionality`.
- [ ] `OrdLogic for (A, B)`: laws are unprovable because we don't import the laws for `<A as OrdLogic>` and `<B as OrdLogic>`, I don't know how to convince Creusot to import them.
- [ ] `slice::Iter`: cannot prove `produces_refl` and `produces_trans`, that's sad since the goal is basically `s = empty ++ s`. Note that `IterMut::produces_refl` proves, but not `IterMut::produces_trans` (weird).
- [ ] `Iterator::map_inv`: needs more investigation, see what the test suite does.
- [ ] `iter::Fuse`: investigate `is_fused`: cannot prove `^self = next`, maybe something missing in `completed`.
- [ ] Lots of laws in `impl Ordlogic for Option` don't prove, I suspect for the same reason as `(A, B)`.
- [ ] `iter::MapInv`, `iter::Zip`, `iter::Zip`, `option::IntoIter`, `option::IntoMut`, `vec::IntoIter` all could not prove `produces_trans`. Needs more investigation, and a comparison with the test suite.
- [ ] `Snapshot::deref`: why does it even generate a proof obligation ? (And why is there an exception for allowing `Snapshot::deref` to be `#[logic]` ?)
- [ ] `ops::FnMutExt`: cannot prove `postcondition_mut_unnest`, `unnest_refl` and `unnest_trans`. They should probably be `#[trusted]` since `unnest` is `#[trusted]`.

**Comment by arnaudgolfouse** [comment]
Ok, the two `OrdLogic` can be fixed by adding the spec of the laws in `ord_laws_impl!`. There also is a bug in `(A, B)::le_log` and `(A, B)::ge_log`:
```diff
- pearlite! { (self.0 == o.0 && self.1 <= o.1) || self.0 <= o.0 }
+ pearlite! { (self.0 == o.0 && self.1 <= o.1) || self.0 < o.0 }
```

**Comment by arnaudgolfouse** [comment]
Done in #1190
