### ISSUE TITLE
Type invariants cause unsound contracts for unspecified functions

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot#878]
When an external function has no contract, creusot might still add preconditions for type invariants. This interferes with the elaboration which adds `requires { false }` to those functions, resulting in an unsound contract. 

An example is `PartialEq::ne`

cc @voidc

**Comment by voidc** [comment]
Why is this unsound? After all `false /\ inv(arg)` is still false.

**Comment by voidc** [comment]
There seems to be a more general issue with extern functions. I tested this example:
```rust
pub fn test() {
    let mut v = vec![1, 2, 2, 3];
    v.dedup();
    proof_assert! { v@.len() == 3 };
}
```
Since there is no extern spec for `dedup`, I would expect it to get a `requires(false)`.
However, the check [`ctx.externs.get(def_id.krate).is_some()`](https://github.com/xldenis/creusot/blob/7490b0c5434c18fc5669fdc6377e9c60bc000972/creusot/src/translation/specification.rs#L285) fails because `ctx.externs` only contains [direct](https://github.com/xldenis/creusot/blob/7490b0c5434c18fc5669fdc6377e9c60bc000972/creusot/src/metadata.rs#L210) dependencies of the current crate.
`dedup` comes from the `alloc` crate which is a dep of `std` and thus not direct.
The same issue for item from `core`.
I think the fix should be just removing the `is_direct` check.

**Comment by xldenis** [comment]
That's weird because it definitely _used_ to work, though perhaps I never tested with transitive dependencies. Your explanation makes sense, I had figured it was because `inv` was being added and preventing the `false` check from passing.

**Comment by voidc** [comment]
Hmm, maybe something changed when updating the rustc version?
